services:
  peruhurt-hw-server:
    container_name: peruhurt-hw-server
    image: jorgecayetano1/peruhurt-hw-server:prod
    build:
      context: ./docker
      args:
        - STEAMAPPID=${STEAMAPPID}
        - STEAMAPP=${STEAMAPP}
        - STEAMAPPDIR=${STEAMAPPDIR}
    environment:
      - STEAMAPPID=${STEAMAPPID}
      - STEAMAPP=${STEAMAPP}
      - STEAMAPPDIR=${STEAMAPPDIR}
    ports:
      - "12871:12871/udp"
      - "12881:12881/udp"
    volumes:
      - hurtworld_data:/home/steam/hurtworld
    restart: always

volumes:
  hurtworld_data:
    external: false
